#!/usr/bin/env python3
"""
Generate the FrugalNav maps. Two worlds, one binary: the node loads its obstacle /
marker scene from config/<map>_scene.txt at runtime, so the same node flies either
map. Obstacles are TALL (14 m) so they are real collision hazards at flight
altitude (2-8 m), not things the drone floats over.

    python3 tools/gen_maps.py
writes, for map in {demo, canopy}:
    worlds/<map>.world
    config/<map>_scene.txt      (target/start/hard/pillar/marker lines)
"""
import math
import os
import random

HERE = os.path.dirname(os.path.abspath(__file__))
PKG = os.path.dirname(HERE)
OBST_H = 14.0                      # obstacle height (m) -> collidable at flight altitude


# ------------------------------------------------------------------ helpers
def cyl(name, x, y, r, h, rgba, z=None):
    z = h / 2 if z is None else z
    c = " ".join(map(str, rgba))
    return (f'    <model name="{name}"><static>true</static><pose>{x:.3f} {y:.3f} {z:.3f} 0 0 0</pose>'
            f'<link name="l"><collision name="c"><geometry><cylinder><radius>{r}</radius>'
            f'<length>{h}</length></cylinder></geometry></collision>'
            f'<visual name="v"><geometry><cylinder><radius>{r}</radius><length>{h}</length></cylinder></geometry>'
            f'<material><ambient>{c}</ambient><diffuse>{c}</diffuse></material></visual></link></model>')


def box(name, x, y, sx, sy, sz, rgba, z=None):
    z = sz / 2 if z is None else z
    c = " ".join(map(str, rgba))
    return (f'    <model name="{name}"><static>true</static><pose>{x:.3f} {y:.3f} {z:.3f} 0 0 0</pose>'
            f'<link name="l"><collision name="c"><geometry><box><size>{sx} {sy} {sz}</size></box></geometry></collision>'
            f'<visual name="v"><geometry><box><size>{sx} {sy} {sz}</size></box></geometry>'
            f'<material><ambient>{c}</ambient><diffuse>{c}</diffuse></material></visual></link></model>')


def flat(name, x, y, sx, sy, rgba, z=0.03):
    c = " ".join(map(str, rgba))
    return (f'    <model name="{name}"><static>true</static><pose>{x:.3f} {y:.3f} {z} 0 0 0</pose>'
            f'<link name="l"><visual name="v"><geometry><box><size>{sx} {sy} 0.05</size></box></geometry>'
            f'<material><ambient>{c}</ambient></material></visual></link></model>')


def disc(name, x, y, r, rgba, z):
    c = " ".join(map(str, rgba))
    return (f'    <model name="{name}"><static>true</static><pose>{x:.3f} {y:.3f} {z:.2f} 0 0 0</pose>'
            f'<link name="l"><visual name="v"><geometry><cylinder><radius>{r}</radius><length>0.3</length></cylinder></geometry>'
            f'<material><ambient>{c}</ambient><diffuse>{c}</diffuse></material></visual></link></model>')


def world(name, bodies, ground_rgba, bg="0.62 0.66 0.72 1", fog_density=0.02):
    body = "\n".join(bodies)
    return f"""<?xml version="1.0" ?>
<!-- GENERATED by tools/gen_maps.py -- do not edit by hand. -->
<sdf version="1.6">
  <world name="{name}">
    <gravity>0 0 -9.81</gravity>
    <scene><ambient>0.5 0.52 0.55 1</ambient><background>{bg}</background><shadows>true</shadows>
      <fog><color>{bg}</color><type>linear</type><start>16</start><end>90</end><density>{fog_density}</density></fog></scene>
    <light name="sun" type="directional"><cast_shadows>true</cast_shadows><pose>0 0 40 0 0 0</pose>
      <diffuse>0.9 0.9 0.9 1</diffuse><specular>0.2 0.2 0.2 1</specular><direction>-0.4 0.3 -0.9</direction></light>
    <model name="ground"><static>true</static><link name="link">
      <collision name="c"><geometry><plane><normal>0 0 1</normal><size>400 400</size></plane></geometry></collision>
      <visual name="v"><geometry><plane><normal>0 0 1</normal><size>400 400</size></plane></geometry>
      <material><ambient>{' '.join(map(str, ground_rgba))}</ambient><diffuse>{' '.join(map(str, ground_rgba))}</diffuse></material></visual></link></model>
{body}
    <plugin name="gazebo_ros_state" filename="libgazebo_ros_state.so"><ros><namespace>/gazebo</namespace></ros><update_rate>0.0</update_rate></plugin>
    <physics name="ode" type="ode"><max_step_size>0.004</max_step_size><real_time_update_rate>250</real_time_update_rate></physics>
  </world>
</sdf>
"""


def scene_file(target, start, hard, obstacles, markers):
    lines = [f"target {target[0]:.3f} {target[1]:.3f}",
             f"start {start[0]:.3f} {start[1]:.3f}",
             f"hard {hard[0]:.3f} {hard[1]:.3f} {hard[2]:.3f}"]
    for (x, y, r) in obstacles:
        lines.append(f"pillar {x:.3f} {y:.3f} {r:.3f}")
    for (x, y) in markers:
        lines.append(f"marker {x:.3f} {y:.3f}")
    return "\n".join(lines) + "\n"


def grid_markers(obstacles, xr, yr, step=7, clr=2.5):
    out = []
    for mx in range(xr[0], xr[1] + 1, step):
        for my in range(yr[0], yr[1] + 1, step):
            if all(math.hypot(mx - ox, my - oy) > orr + clr for (ox, oy, orr) in obstacles):
                out.append((float(mx), float(my)))
    return out


# ------------------------------------------------------------------ DEMO map
def build_demo():
    start, target = (58.0, 24.0), (0.0, 0.0)
    seg = (target[0] - start[0], target[1] - start[1]); n = math.hypot(*seg)
    axis = (seg[0] / n, seg[1] / n); left = (-axis[1], axis[0])
    def lat(f, l):
        p = (start[0] + f * seg[0], start[1] + f * seg[1]); return (p[0] + l * left[0], p[1] + l * left[1])
    # tall towers (wider + 14 m) -- real collision hazards
    obstacles = [(*lat(0.30, 2.4), 2.2), (*lat(0.44, -2.8), 2.2), (*lat(0.56, 2.6), 2.6),
                 (*lat(0.70, -2.4), 2.2), (*lat(0.82, 1.8), 2.0)]
    hard = (start[0] + 0.38 * seg[0], start[1] + 0.38 * seg[1], 8.0)
    markers = grid_markers(obstacles, (4, 60), (0, 30))

    XMIN, XMAX, YMIN, YMAX = -8.0, 66.0, -10.0, 34.0
    bodies = []
    t = 0.4
    for nm, x, y, sx, sy in [("wall_s", (XMIN+XMAX)/2, YMIN, XMAX-XMIN, t),
                             ("wall_n", (XMIN+XMAX)/2, YMAX, XMAX-XMIN, t),
                             ("wall_w", XMIN, (YMIN+YMAX)/2, t, YMAX-YMIN),
                             ("wall_e", XMAX, (YMIN+YMAX)/2, t, YMAX-YMIN)]:
        bodies.append(box(nm, x, y, sx, sy, 3.0, (0.20, 0.24, 0.30, 1)))
    bodies.append(disc("hard_patch", hard[0], hard[1], hard[2], (0.96, 0.62, 0.04, 0.22), 0.03))
    for i, (x, y, r) in enumerate(obstacles):
        bodies.append(cyl(f"tower{i}", x, y, r, OBST_H, (0.33, 0.34, 0.4, 1)))
    for i, (x, y, sx, sy, sz) in enumerate([(30, 30, 6, 5, 12), (18, -6, 5, 6, 10), (46, -5, 7, 4, 13)]):
        bodies.append(box(f"building{i}", x, y, sx, sy, sz, (0.26, 0.29, 0.36, 1)))
    for i, (x, y) in enumerate(markers):
        bodies.append(flat(f"marker{i}", x, y, 0.9, 0.9, (0.95, 0.95, 0.98, 1)))
    bodies.append(cyl("target_B", *target, 0.6, 3.0, (0.98, 0.75, 0.14, 1), z=1.5))
    bodies.append(cyl("start_pad", *start, 1.0, 0.04, (0.20, 0.83, 0.44, 0.85), z=0.02))

    with open(os.path.join(PKG, "worlds", "demo.world"), "w") as f:
        f.write(world("demo", bodies, (0.13, 0.15, 0.2)))
    with open(os.path.join(PKG, "config", "demo_scene.txt"), "w") as f:
        f.write(scene_file(target, start, hard, obstacles, markers))
    return len(obstacles), len(markers)


# ------------------------------------------------------------------ CANOPY map
def build_canopy():
    rng = random.Random(7)
    start, target = (56.0, 15.0), (2.0, 15.0)
    hard = (30.0, 15.0, 9.0)                       # dense-canopy "GPS-black" core
    # forest: jittered grid of tree trunks, leave the start/target pads clear
    trees = []
    for gx in range(6, 55, 6):
        for gy in range(2, 29, 6):
            x = gx + rng.uniform(-1.6, 1.6); y = gy + rng.uniform(-1.6, 1.6)
            if math.hypot(x - start[0], y - start[1]) < 4 or math.hypot(x - target[0], y - target[1]) < 4:
                continue
            trees.append((x, y, rng.uniform(0.5, 0.8)))
    markers = grid_markers(trees, (4, 58), (2, 28), step=6, clr=1.4)

    bodies = []
    bodies.append(disc("gps_black", hard[0], hard[1], hard[2], (0.10, 0.18, 0.10, 0.30), 0.03))
    for i, (x, y, r) in enumerate(trees):
        h = 11.0 + rng.uniform(-1.5, 2.5)
        bodies.append(cyl(f"trunk{i}", x, y, r, h, (0.30, 0.22, 0.14, 1)))      # brown trunk
        bodies.append(disc(f"canopy{i}", x, y, r + 2.2, (0.13, 0.34, 0.15, 0.75), h))  # green crown
    for i, (x, y) in enumerate(markers):
        bodies.append(flat(f"marker{i}", x, y, 0.9, 0.9, (0.95, 0.95, 0.98, 1)))
    bodies.append(cyl("target_B", *target, 0.6, 3.0, (0.98, 0.75, 0.14, 1), z=1.5))
    bodies.append(cyl("start_pad", *start, 1.0, 0.04, (0.20, 0.83, 0.44, 0.85), z=0.02))

    obstacles = [(x, y, r) for (x, y, r) in trees]
    with open(os.path.join(PKG, "worlds", "canopy.world"), "w") as f:
        f.write(world("canopy", bodies, (0.10, 0.20, 0.11), bg="0.45 0.55 0.5 1", fog_density=0.035))
    with open(os.path.join(PKG, "config", "canopy_scene.txt"), "w") as f:
        f.write(scene_file(target, start, hard, obstacles, markers))
    return len(trees), len(markers)


# ------------------------------------------------------------------ REAL map
def aruco_tile(name, x, y, mid, size=2.6):
    # a ground tile whose top face shows a REAL ArUco texture (material aruco/<id>),
    # big enough for the downward camera to resolve at flight altitude.
    return (f'    <model name="{name}"><static>true</static><pose>{x:.3f} {y:.3f} 0.02 0 0 0</pose>'
            f'<link name="l"><visual name="v"><geometry><box><size>{size} {size} 0.02</size></box></geometry>'
            f'<material><script><uri>file://materials/scripts</uri>'
            f'<uri>file://materials/textures</uri><name>aruco/{mid}</name></script></material>'
            f'</visual></link></model>')


def build_real():
    # Compact arena for the REAL camera-perception pipeline: fewer, bigger ArUco
    # tiles (unique ids -> known world poses) that the camera genuinely detects.
    start, target = (28.0, 10.0), (2.0, 10.0)
    hard = (15.0, 10.0, 5.0)
    obstacles = [(21.0, 12.5, 1.4), (15.0, 7.0, 1.6), (9.0, 12.0, 1.4)]
    # ArUco markers on a grid (ids 0..N-1), avoiding obstacles
    markers = []  # (id, x, y)
    mid = 0
    for mx in range(4, 29, 6):
        for my in range(3, 18, 5):
            if mid >= 24:
                break
            if all(math.hypot(mx - ox, my - oy) > orr + 2.4 for (ox, oy, orr) in obstacles):
                markers.append((mid, float(mx), float(my))); mid += 1

    bodies = []
    for i, (x, y, r) in enumerate(obstacles):
        bodies.append(cyl(f"tower{i}", x, y, r, OBST_H, (0.33, 0.34, 0.4, 1)))
    bodies.append(disc("hard_patch", hard[0], hard[1], hard[2], (0.96, 0.62, 0.04, 0.20), 0.03))
    for (i, x, y) in markers:
        bodies.append(aruco_tile(f"aruco{i}", x, y, i))
    bodies.append(cyl("target_B", *target, 0.6, 3.0, (0.98, 0.75, 0.14, 1), z=1.5))
    bodies.append(cyl("start_pad", *start, 1.0, 0.04, (0.20, 0.83, 0.44, 0.85), z=0.02))

    with open(os.path.join(PKG, "worlds", "real.world"), "w") as f:
        f.write(world("real", bodies, (0.16, 0.17, 0.2), fog_density=0.015))
    # scene file: obstacles as pillars + markers as "amarker id x y" (with a real id)
    lines = [f"target {target[0]:.3f} {target[1]:.3f}",
             f"start {start[0]:.3f} {start[1]:.3f}",
             f"hard {hard[0]:.3f} {hard[1]:.3f} {hard[2]:.3f}"]
    for (x, y, r) in obstacles:
        lines.append(f"pillar {x:.3f} {y:.3f} {r:.3f}")
    for (i, x, y) in markers:
        lines.append(f"amarker {i} {x:.3f} {y:.3f}")
    with open(os.path.join(PKG, "config", "real_scene.txt"), "w") as f:
        f.write("\n".join(lines) + "\n")
    return len(obstacles), len(markers)


if __name__ == "__main__":
    os.makedirs(os.path.join(PKG, "config"), exist_ok=True)
    do, dm = build_demo()
    co, cm = build_canopy()
    ro, rm = build_real()
    print(f"demo:   {do} towers/buildings, {dm} markers")
    print(f"canopy: {co} trees, {cm} markers")
    print(f"real:   {ro} obstacles, {rm} ArUco markers (ids 0..{rm-1})")
