#!/usr/bin/env python3
"""
Generates the Gazebo worlds and their matching scene files.

Nodes load obstacles and markers from config/<map>_scene.txt at runtime, so one binary
flies any map. Obstacles are 14 m tall so they are real hazards at flight altitude
rather than something the drone floats over.

    python tools/gen_maps.py          all maps
    python tools/gen_maps.py real     only real + real_dense, leaves the sandbox alone
"""
import math
import os
import random

HERE = os.path.dirname(os.path.abspath(__file__))
PKG = os.path.dirname(HERE)
OBST_H = 14.0                      # obstacle height (m) -> collidable at flight altitude


# ------------------------------------------------------------------ helpers
def cyl(name, x, y, r, h, rgba, z=None):
    z = h / 2 if z is None else z
    c = " ".join(map(str, rgba))
    return (f'    <model name="{name}"><static>true</static><pose>{x:.3f} {y:.3f} {z:.3f} 0 0 0</pose>'
            f'<link name="l"><collision name="c"><geometry><cylinder><radius>{r}</radius>'
            f'<length>{h}</length></cylinder></geometry></collision>'
            f'<visual name="v"><geometry><cylinder><radius>{r}</radius><length>{h}</length></cylinder></geometry>'
            f'<material><ambient>{c}</ambient><diffuse>{c}</diffuse></material></visual></link></model>')


def box(name, x, y, sx, sy, sz, rgba, z=None):
    z = sz / 2 if z is None else z
    c = " ".join(map(str, rgba))
    return (f'    <model name="{name}"><static>true</static><pose>{x:.3f} {y:.3f} {z:.3f} 0 0 0</pose>'
            f'<link name="l"><collision name="c"><geometry><box><size>{sx} {sy} {sz}</size></box></geometry></collision>'
            f'<visual name="v"><geometry><box><size>{sx} {sy} {sz}</size></box></geometry>'
            f'<material><ambient>{c}</ambient><diffuse>{c}</diffuse></material></visual></link></model>')


def flat(name, x, y, sx, sy, rgba, z=0.03):
    c = " ".join(map(str, rgba))
    return (f'    <model name="{name}"><static>true</static><pose>{x:.3f} {y:.3f} {z} 0 0 0</pose>'
            f'<link name="l"><visual name="v"><geometry><box><size>{sx} {sy} 0.05</size></box></geometry>'
            f'<material><ambient>{c}</ambient></material></visual></link></model>')


def haze(name, x, y, sx, sy, z, alpha=0.88):
    # A translucent slab with NO collision: a low haze/cloud bank. A camera looking down
    # through it loses contrast, so markers underneath stop resolving. Flying below the
    # slab clears the view again -- which is what forces the altitude change.
    c = f"0.72 0.74 0.78 {alpha}"
    return (f'    <model name="{name}"><static>true</static><pose>{x:.3f} {y:.3f} {z:.2f} 0 0 0</pose>'
            f'<link name="l"><visual name="v"><geometry><box><size>{sx} {sy} 0.15</size></box></geometry>'
            f'<material><ambient>{c}</ambient><diffuse>{c}</diffuse></material>'
            f'<transparency>{1.0 - alpha:.2f}</transparency></visual></link></model>')


def disc(name, x, y, r, rgba, z):
    c = " ".join(map(str, rgba))
    return (f'    <model name="{name}"><static>true</static><pose>{x:.3f} {y:.3f} {z:.2f} 0 0 0</pose>'
            f'<link name="l"><visual name="v"><geometry><cylinder><radius>{r}</radius><length>0.3</length></cylinder></geometry>'
            f'<material><ambient>{c}</ambient><diffuse>{c}</diffuse></material></visual></link></model>')


def world(name, bodies, ground_rgba, bg="0.62 0.66 0.72 1", fog_density=0.02):
    body = "\n".join(bodies)
    return f"""<?xml version="1.0" ?>
<!-- GENERATED by tools/gen_maps.py -- do not edit by hand. -->
<sdf version="1.6">
  <world name="{name}">
    <gravity>0 0 -9.81</gravity>
    <scene><ambient>0.5 0.52 0.55 1</ambient><background>{bg}</background><shadows>true</shadows>
      <fog><color>{bg}</color><type>linear</type><start>16</start><end>90</end><density>{fog_density}</density></fog></scene>
    <light name="sun" type="directional"><cast_shadows>true</cast_shadows><pose>0 0 40 0 0 0</pose>
      <diffuse>0.9 0.9 0.9 1</diffuse><specular>0.2 0.2 0.2 1</specular><direction>-0.4 0.3 -0.9</direction></light>
    <model name="ground"><static>true</static><link name="link">
      <collision name="c"><geometry><plane><normal>0 0 1</normal><size>400 400</size></plane></geometry></collision>
      <visual name="v"><geometry><plane><normal>0 0 1</normal><size>400 400</size></plane></geometry>
      <material><ambient>{' '.join(map(str, ground_rgba))}</ambient><diffuse>{' '.join(map(str, ground_rgba))}</diffuse></material></visual></link></model>
{body}
    <plugin name="gazebo_ros_state" filename="libgazebo_ros_state.so"><ros><namespace>/gazebo</namespace></ros><update_rate>0.0</update_rate></plugin>
    <physics name="ode" type="ode"><max_step_size>0.004</max_step_size><real_time_update_rate>250</real_time_update_rate></physics>
  </world>
</sdf>
"""


def scene_file(target, start, hard, obstacles, markers):
    lines = [f"target {target[0]:.3f} {target[1]:.3f}",
             f"start {start[0]:.3f} {start[1]:.3f}",
             f"hard {hard[0]:.3f} {hard[1]:.3f} {hard[2]:.3f}"]
    for (x, y, r) in obstacles:
        lines.append(f"pillar {x:.3f} {y:.3f} {r:.3f}")
    for (x, y) in markers:
        lines.append(f"marker {x:.3f} {y:.3f}")
    return "\n".join(lines) + "\n"


def grid_markers(obstacles, xr, yr, step=7, clr=2.5):
    out = []
    for mx in range(xr[0], xr[1] + 1, step):
        for my in range(yr[0], yr[1] + 1, step):
            if all(math.hypot(mx - ox, my - oy) > orr + clr for (ox, oy, orr) in obstacles):
                out.append((float(mx), float(my)))
    return out


# ------------------------------------------------------------------ DEMO map
def build_demo():
    start, target = (58.0, 24.0), (0.0, 0.0)
    seg = (target[0] - start[0], target[1] - start[1]); n = math.hypot(*seg)
    axis = (seg[0] / n, seg[1] / n); left = (-axis[1], axis[0])
    def lat(f, l):
        p = (start[0] + f * seg[0], start[1] + f * seg[1]); return (p[0] + l * left[0], p[1] + l * left[1])
    # tall towers (wider + 14 m) -- real collision hazards
    obstacles = [(*lat(0.30, 2.4), 2.2), (*lat(0.44, -2.8), 2.2), (*lat(0.56, 2.6), 2.6),
                 (*lat(0.70, -2.4), 2.2), (*lat(0.82, 1.8), 2.0)]
    hard = (start[0] + 0.38 * seg[0], start[1] + 0.38 * seg[1], 8.0)
    markers = grid_markers(obstacles, (4, 60), (0, 30))

    XMIN, XMAX, YMIN, YMAX = -8.0, 66.0, -10.0, 34.0
    bodies = []
    t = 0.4
    for nm, x, y, sx, sy in [("wall_s", (XMIN+XMAX)/2, YMIN, XMAX-XMIN, t),
                             ("wall_n", (XMIN+XMAX)/2, YMAX, XMAX-XMIN, t),
                             ("wall_w", XMIN, (YMIN+YMAX)/2, t, YMAX-YMIN),
                             ("wall_e", XMAX, (YMIN+YMAX)/2, t, YMAX-YMIN)]:
        bodies.append(box(nm, x, y, sx, sy, 3.0, (0.20, 0.24, 0.30, 1)))
    bodies.append(disc("hard_patch", hard[0], hard[1], hard[2], (0.96, 0.62, 0.04, 0.22), 0.03))
    for i, (x, y, r) in enumerate(obstacles):
        bodies.append(cyl(f"tower{i}", x, y, r, OBST_H, (0.33, 0.34, 0.4, 1)))
    for i, (x, y, sx, sy, sz) in enumerate([(30, 30, 6, 5, 12), (18, -6, 5, 6, 10), (46, -5, 7, 4, 13)]):
        bodies.append(box(f"building{i}", x, y, sx, sy, sz, (0.26, 0.29, 0.36, 1)))
    for i, (x, y) in enumerate(markers):
        bodies.append(flat(f"marker{i}", x, y, 0.9, 0.9, (0.95, 0.95, 0.98, 1)))
    bodies.append(cyl("target_B", *target, 0.6, 3.0, (0.98, 0.75, 0.14, 1), z=1.5))
    bodies.append(cyl("start_pad", *start, 1.0, 0.04, (0.20, 0.83, 0.44, 0.85), z=0.02))

    with open(os.path.join(PKG, "worlds", "demo.world"), "w") as f:
        f.write(world("demo", bodies, (0.13, 0.15, 0.2)))
    with open(os.path.join(PKG, "config", "demo_scene.txt"), "w") as f:
        f.write(scene_file(target, start, hard, obstacles, markers))
    return len(obstacles), len(markers)


# ------------------------------------------------------------------ CANOPY map
def build_canopy():
    rng = random.Random(7)
    start, target = (56.0, 15.0), (2.0, 15.0)
    hard = (30.0, 15.0, 9.0)                       # dense-canopy "GPS-black" core
    # forest: jittered grid of tree trunks, leave the start/target pads clear
    trees = []
    for gx in range(6, 55, 6):
        for gy in range(2, 29, 6):
            x = gx + rng.uniform(-1.6, 1.6); y = gy + rng.uniform(-1.6, 1.6)
            if math.hypot(x - start[0], y - start[1]) < 4 or math.hypot(x - target[0], y - target[1]) < 4:
                continue
            trees.append((x, y, rng.uniform(0.5, 0.8)))
    markers = grid_markers(trees, (4, 58), (2, 28), step=6, clr=1.4)

    bodies = []
    bodies.append(disc("gps_black", hard[0], hard[1], hard[2], (0.10, 0.18, 0.10, 0.30), 0.03))
    for i, (x, y, r) in enumerate(trees):
        h = 11.0 + rng.uniform(-1.5, 2.5)
        bodies.append(cyl(f"trunk{i}", x, y, r, h, (0.30, 0.22, 0.14, 1)))      # brown trunk
        bodies.append(disc(f"canopy{i}", x, y, r + 2.2, (0.13, 0.34, 0.15, 0.75), h))  # green crown
    for i, (x, y) in enumerate(markers):
        bodies.append(flat(f"marker{i}", x, y, 0.9, 0.9, (0.95, 0.95, 0.98, 1)))
    bodies.append(cyl("target_B", *target, 0.6, 3.0, (0.98, 0.75, 0.14, 1), z=1.5))
    bodies.append(cyl("start_pad", *start, 1.0, 0.04, (0.20, 0.83, 0.44, 0.85), z=0.02))

    obstacles = [(x, y, r) for (x, y, r) in trees]
    with open(os.path.join(PKG, "worlds", "canopy.world"), "w") as f:
        f.write(world("canopy", bodies, (0.10, 0.20, 0.11), bg="0.45 0.55 0.5 1", fog_density=0.035))
    with open(os.path.join(PKG, "config", "canopy_scene.txt"), "w") as f:
        f.write(scene_file(target, start, hard, obstacles, markers))
    return len(trees), len(markers)


# ------------------------------------------------------------------ REAL map
def aruco_tile(name, x, y, mid, size=2.6):
    # a ground tile whose top face shows a REAL ArUco texture (material aruco/<id>),
    # big enough for the downward camera to resolve at flight altitude.
    return (f'    <model name="{name}"><static>true</static><pose>{x:.3f} {y:.3f} 0.02 0 0 0</pose>'
            f'<link name="l"><visual name="v"><geometry><box><size>{size} {size} 0.02</size></box></geometry>'
            f'<material><script><uri>file://materials/scripts</uri>'
            f'<uri>file://materials/textures</uri><name>aruco/{mid}</name></script></material>'
            f'</visual></link></model>')


def build_real():
    # Compact arena for the REAL camera-perception pipeline: fewer, bigger ArUco
    # tiles (unique ids -> known world poses) that the camera genuinely detects.
    start, target = (28.0, 10.0), (2.0, 10.0)
    hard = (15.0, 10.0, 5.0)
    obstacles = [(21.0, 12.5, 1.4), (15.0, 7.0, 1.6), (9.0, 12.0, 1.4)]
    # Dense ArUco grid (ids 0..N-1). A ~4 m step keeps a marker inside the camera
    # footprint the whole way, and the grid runs THROUGH the target (x from 0) so fixes
    # don't vanish on arrival -- sparse markers let the drift-prone VIO wander off-field.
    markers = []  # (id, x, y)
    mid = 0
    for mx in range(0, 30, 4):
        for my in range(3, 18, 4):
            if mid >= 60:
                break
            if all(math.hypot(mx - ox, my - oy) > orr + 2.0 for (ox, oy, orr) in obstacles):
                markers.append((mid, float(mx), float(my))); mid += 1

    bodies = []
    for i, (x, y, r) in enumerate(obstacles):
        bodies.append(cyl(f"tower{i}", x, y, r, OBST_H, (0.33, 0.34, 0.4, 1)))
    bodies.append(disc("hard_patch", hard[0], hard[1], hard[2], (0.96, 0.62, 0.04, 0.20), 0.03))
    for (i, x, y) in markers:
        bodies.append(aruco_tile(f"aruco{i}", x, y, i))
    bodies.append(cyl("target_B", *target, 0.6, 3.0, (0.98, 0.75, 0.14, 1), z=1.5))
    bodies.append(cyl("start_pad", *start, 1.0, 0.04, (0.20, 0.83, 0.44, 0.85), z=0.02))

    with open(os.path.join(PKG, "worlds", "real.world"), "w") as f:
        f.write(world("real", bodies, (0.16, 0.17, 0.2), fog_density=0.015))
    # scene file: obstacles as pillars + markers as "amarker id x y" (with a real id)
    lines = [f"target {target[0]:.3f} {target[1]:.3f}",
             f"start {start[0]:.3f} {start[1]:.3f}",
             f"hard {hard[0]:.3f} {hard[1]:.3f} {hard[2]:.3f}"]
    for (x, y, r) in obstacles:
        lines.append(f"pillar {x:.3f} {y:.3f} {r:.3f}")
    for (i, x, y) in markers:
        lines.append(f"amarker {i} {x:.3f} {y:.3f}")
    with open(os.path.join(PKG, "config", "real_scene.txt"), "w") as f:
        f.write("\n".join(lines) + "\n")
    return len(obstacles), len(markers)


def build_real_dense():
    # A big, DENSE version of the REAL camera arena: a long corridor packed with tall
    # obstacles and a thick grid of UNIQUE ArUco tiles, so the drone always has a fix
    # in view while it threads a cluttered field on real vision alone.
    rng = random.Random(11)
    start, target = (46.0, 15.0), (2.0, 15.0)
    hard = (24.0, 15.0, 8.0)                       # "GPS-black" core
    # jittered grid of tall pillars, leaving the start/target pads clear
    obstacles = []
    for gx in range(8, 43, 7):
        for gy in range(6, 25, 8):
            x = gx + rng.uniform(-1.8, 1.8); y = gy + rng.uniform(-1.8, 1.8)
            if (math.hypot(x - start[0], y - start[1]) < 6 or
                    math.hypot(x - target[0], y - target[1]) < 6):
                continue
            obstacles.append((x, y, rng.uniform(1.3, 1.7)))
    # dense ArUco tile grid (unique ids 0..N-1), clear of the obstacles.
    # ~4 m step + grid starting at x=0 keeps a marker in view all the way to the
    # target at (2,15); a drift-prone VIO needs continuous fixes, not sparse ones.
    markers = []; mid = 0
    for mx in range(0, 48, 4):
        for my in range(4, 27, 4):
            if mid >= 90:
                break
            if all(math.hypot(mx - ox, my - oy) > orr + 2.0 for (ox, oy, orr) in obstacles):
                markers.append((mid, float(mx), float(my))); mid += 1

    bodies = []
    for i, (x, y, r) in enumerate(obstacles):
        bodies.append(cyl(f"tower{i}", x, y, r, OBST_H, (0.33, 0.34, 0.4, 1)))
    bodies.append(disc("hard_patch", hard[0], hard[1], hard[2], (0.96, 0.62, 0.04, 0.18), 0.03))
    for (i, x, y) in markers:
        bodies.append(aruco_tile(f"aruco{i}", x, y, i))
    bodies.append(cyl("target_B", *target, 0.6, 3.0, (0.98, 0.75, 0.14, 1), z=1.5))
    bodies.append(cyl("start_pad", *start, 1.0, 0.04, (0.20, 0.83, 0.44, 0.85), z=0.02))

    with open(os.path.join(PKG, "worlds", "real_dense.world"), "w") as f:
        f.write(world("real_dense", bodies, (0.15, 0.16, 0.19), fog_density=0.02))
    lines = [f"target {target[0]:.3f} {target[1]:.3f}",
             f"start {start[0]:.3f} {start[1]:.3f}",
             f"hard {hard[0]:.3f} {hard[1]:.3f} {hard[2]:.3f}"]
    for (x, y, r) in obstacles:
        lines.append(f"pillar {x:.3f} {y:.3f} {r:.3f}")
    for (i, x, y) in markers:
        lines.append(f"amarker {i} {x:.3f} {y:.3f}")
    with open(os.path.join(PKG, "config", "real_dense_scene.txt"), "w") as f:
        f.write("\n".join(lines) + "\n")
    return len(obstacles), len(markers)


def build_city():
    # Dense city block for demo 3. Most buildings are LOW (under flight altitude) so the
    # drone overflies them and the horizontal laser never sees them -- they are there for
    # density and for camera texture. The scattered TOWERS punch through the flight level
    # and are the real obstacles. Towers are kept at least two grid cells apart so the
    # reactive potential field always has a way through.
    rng = random.Random(21)
    start, target = (64.0, 22.0), (6.0, 22.0)
    hard = (35.0, 22.0, 10.0)
    FLIGHT_Z = 5.0

    gx = list(range(6, 69, 8))       # 8 columns
    gy = list(range(4, 45, 8))       # 6 rows  -> a packed grid of city blocks
    buildings, towers = [], []
    for i, bx in enumerate(gx):
        for j, by in enumerate(gy):
            x = bx + rng.uniform(-0.6, 0.6)
            y = by + rng.uniform(-0.6, 0.6)
            if (math.hypot(x - start[0], y - start[1]) < 7 or
                    math.hypot(x - target[0], y - target[1]) < 7):
                continue
            # Leave an avenue along the start->target line. The blocks either side give the
            # city its density; the avenue is where the flying happens and gets filled with
            # mixed obstacles below.
            if abs(y - start[1]) < 9:
                continue
            tall = (i % 2 == 0 and j % 2 == 0)
            sx, sy = rng.uniform(4.4, 5.2), rng.uniform(4.4, 5.2)
            h = rng.uniform(12.0, 28.0) if tall else rng.uniform(2.0, 4.2)
            buildings.append((x, y, sx, sy, h))
            if h > FLIGHT_Z:
                towers.append((x, y, sx, sy, h))

    # Street clutter: masts, poles and pillars of mixed size scattered through the whole
    # arena, including straight across the flight corridor. Rejection sampling keeps a
    # guaranteed CLEAR_GAP between every pair of obstacles, so however dense it gets there
    # is always a passage the reactive avoider can take.
    CLEAR_GAP = 6.4
    round_obs = [(x, y, max(sx, sy) * 0.5) for (x, y, sx, sy, h) in towers]
    clutter = []
    for _ in range(3000):
        x = rng.uniform(9, 61)
        y = start[1] + rng.uniform(-8.5, 8.5)          # inside the avenue
        if (math.hypot(x - start[0], y - start[1]) < 6 or
                math.hypot(x - target[0], y - target[1]) < 6):
            continue
        kind = rng.random()
        r = (rng.uniform(0.45, 0.8) if kind < 0.5 else            # slim masts
             rng.uniform(1.0, 1.6) if kind < 0.82 else            # mid pillars
             rng.uniform(2.0, 3.0))                               # fat blocks
        if any(math.hypot(x - ox, y - oy) < r + orr + CLEAR_GAP for (ox, oy, orr) in round_obs):
            continue
        if any(abs(x - bx) < sx / 2 + r + 1.5 and abs(y - by) < sy / 2 + r + 1.5
               for (bx, by, sx, sy, h) in buildings):
            continue
        h = rng.uniform(9.0, 19.0)
        clutter.append((x, y, r, h)); round_obs.append((x, y, r))

    # Two low haze banks across the corridor. Cruising above them washes the ground out;
    # the drone has to drop below to get its markers back.
    hazes = [(46.0, 22.0, 15.0, 26.0, 3.6), (20.0, 22.0, 13.0, 26.0, 3.6)]

    # ArUco tiles down the streets: a 2.6 m tile needs half its width clear of anything
    markers, mid = [], 0
    for mx in range(5, 70, 4):
        for my in range(4, 46, 4):
            if mid >= 96:
                break
            if any(abs(mx - bx) < sx / 2 + 1.45 and abs(my - by) < sy / 2 + 1.45
                   for (bx, by, sx, sy, h) in buildings):
                continue
            if any(math.hypot(mx - ox, my - oy) < orr + 1.6 for (ox, oy, orr) in round_obs):
                continue
            markers.append((mid, float(mx), float(my))); mid += 1

    bodies = []
    for i, (x, y, r, h) in enumerate(clutter):
        g = rng.uniform(0.30, 0.44)
        bodies.append(cyl(f"mast{i}", x, y, r, h, (g, g + 0.01, g + 0.05, 1)))
    for i, (hx, hy, hsx, hsy, hz) in enumerate(hazes):
        bodies.append(haze(f"haze{i}", hx, hy, hsx, hsy, hz))
    for i, (x, y, sx, sy, h) in enumerate(buildings):
        shade = rng.uniform(0.26, 0.46)
        rgba = (shade, shade + 0.02, shade + 0.06, 1)
        bodies.append(box(f"bldg{i}", x, y, sx, sy, h, rgba))
    bodies.append(disc("hard_patch", hard[0], hard[1], hard[2], (0.96, 0.62, 0.04, 0.16), 0.03))
    for (i, x, y) in markers:
        bodies.append(aruco_tile(f"aruco{i}", x, y, i))
    bodies.append(cyl("target_B", *target, 0.6, 3.0, (0.98, 0.75, 0.14, 1), z=1.5))
    bodies.append(cyl("start_pad", *start, 1.0, 0.04, (0.20, 0.83, 0.44, 0.85), z=0.02))

    with open(os.path.join(PKG, "worlds", "city.world"), "w") as f:
        f.write(world("city", bodies, (0.17, 0.17, 0.19), bg="0.58 0.60 0.65 1", fog_density=0.045))

    lines = [f"target {target[0]:.3f} {target[1]:.3f}",
             f"start {start[0]:.3f} {start[1]:.3f}",
             f"hard {hard[0]:.3f} {hard[1]:.3f} {hard[2]:.3f}"]
    # `building` = accurate box for the RViz reference; `pillar` = circular approximation
    # so the map-based demo-2 navigator can also fly this map.
    for (x, y, sx, sy, h) in towers:
        lines.append(f"building {x:.3f} {y:.3f} {sx:.3f} {sy:.3f} {h:.3f}")
    for (x, y, sx, sy, h) in towers:
        lines.append(f"pillar {x:.3f} {y:.3f} {max(sx, sy) * 0.5:.3f}")
    for (x, y, r, h) in clutter:
        lines.append(f"pillar {x:.3f} {y:.3f} {r:.3f}")
    for (i, x, y) in markers:
        lines.append(f"amarker {i} {x:.3f} {y:.3f}")
    with open(os.path.join(PKG, "config", "city_scene.txt"), "w") as f:
        f.write("\n".join(lines) + "\n")
    return len(buildings), len(towers) + len(clutter), len(markers)


def build_metro():
    """Demo 3 'metro': a big, dense, real-life-like downtown. A varied skyline (tall towers,
    mid-rises, low blocks), heavy street clutter down the flight avenue, and THREE low haze
    banks so the drone drops and climbs three times on the way in. Dense ArUco tiles run the
    whole corridor and THROUGH the target, so a drift-prone landmark navigator gets constant
    fixes -- the map is hard on obstacles, not on localisation."""
    rng = random.Random(37)
    start, target = (68.0, 26.0), (6.0, 26.0)
    hard = (37.0, 26.0, 11.0)
    FLIGHT_Z = 5.0

    # skyline grid: every third block is a tall tower (a real obstacle), the rest are
    # mid-rises or low blocks (overflown -- there for density + camera texture).
    gx = list(range(6, 70, 7))
    gy = list(range(4, 50, 7))
    buildings, towers = [], []
    for i, bx in enumerate(gx):
        for j, by in enumerate(gy):
            x = bx + rng.uniform(-0.6, 0.6)
            y = by + rng.uniform(-0.6, 0.6)
            if (math.hypot(x - start[0], y - start[1]) < 8 or
                    math.hypot(x - target[0], y - target[1]) < 8):
                continue
            if abs(y - start[1]) < 9:            # keep the flight avenue clear of buildings
                continue
            kind = (i + j) % 3
            sx, sy = rng.uniform(4.2, 5.2), rng.uniform(4.2, 5.2)
            h = (rng.uniform(16.0, 32.0) if kind == 0 else       # tower
                 rng.uniform(8.0, 13.0) if kind == 1 else        # mid-rise
                 rng.uniform(2.0, 4.2))                          # low block
            buildings.append((x, y, sx, sy, h))
            if h > FLIGHT_Z:
                towers.append((x, y, sx, sy, h))

    # street clutter across the avenue; rejection sampling keeps a guaranteed gap between
    # every pair so the reactive avoider always has a way through.
    CLEAR_GAP = 6.6
    round_obs = [(x, y, max(sx, sy) * 0.5) for (x, y, sx, sy, h) in towers]
    clutter = []
    for _ in range(5000):
        x = rng.uniform(9, 65)
        y = start[1] + rng.uniform(-8.5, 8.5)
        if (math.hypot(x - start[0], y - start[1]) < 6 or
                math.hypot(x - target[0], y - target[1]) < 6):
            continue
        kind = rng.random()
        r = (rng.uniform(0.45, 0.8) if kind < 0.5 else           # slim masts
             rng.uniform(1.0, 1.6) if kind < 0.82 else           # mid pillars
             rng.uniform(2.0, 3.0))                              # fat blocks
        if any(math.hypot(x - ox, y - oy) < r + orr + CLEAR_GAP for (ox, oy, orr) in round_obs):
            continue
        if any(abs(x - bx) < sx / 2 + r + 1.5 and abs(y - by) < sy / 2 + r + 1.5
               for (bx, by, sx, sy, h) in buildings):
            continue
        h = rng.uniform(9.0, 20.0)
        clutter.append((x, y, r, h)); round_obs.append((x, y, r))

    # THREE low haze banks across the corridor -> three descend/climb cycles.
    hazes = [(54.0, 26.0, 12.0, 30.0, 3.6), (37.0, 26.0, 12.0, 30.0, 3.6),
             (20.0, 26.0, 12.0, 30.0, 3.6)]

    # dense ArUco tiles down the flight corridor (y band around 26), running from the start
    # through to the target so fixes never vanish. Corridor-focused keeps us under 100 ids.
    markers, mid = [], 0
    for mx in range(4, 70, 4):
        for my in range(18, 35, 4):
            if mid >= 96:
                break
            if any(math.hypot(mx - ox, my - oy) < orr + 1.6 for (ox, oy, orr) in round_obs):
                continue
            markers.append((mid, float(mx), float(my))); mid += 1

    bodies = []
    for i, (x, y, r, h) in enumerate(clutter):
        g = rng.uniform(0.30, 0.44)
        bodies.append(cyl(f"mast{i}", x, y, r, h, (g, g + 0.01, g + 0.05, 1)))
    for i, (hx, hy, hsx, hsy, hz) in enumerate(hazes):
        bodies.append(haze(f"haze{i}", hx, hy, hsx, hsy, hz))
    for i, (x, y, sx, sy, h) in enumerate(buildings):
        shade = rng.uniform(0.24, 0.46)
        bodies.append(box(f"bldg{i}", x, y, sx, sy, h, (shade, shade + 0.02, shade + 0.07, 1)))
    bodies.append(disc("hard_patch", hard[0], hard[1], hard[2], (0.96, 0.62, 0.04, 0.16), 0.03))
    for (i, x, y) in markers:
        bodies.append(aruco_tile(f"aruco{i}", x, y, i))
    bodies.append(cyl("target_B", *target, 0.6, 3.0, (0.98, 0.75, 0.14, 1), z=1.5))
    bodies.append(cyl("start_pad", *start, 1.0, 0.04, (0.20, 0.83, 0.44, 0.85), z=0.02))

    with open(os.path.join(PKG, "worlds", "metro.world"), "w") as f:
        f.write(world("metro", bodies, (0.16, 0.16, 0.18), bg="0.55 0.58 0.64 1", fog_density=0.05))

    lines = [f"target {target[0]:.3f} {target[1]:.3f}",
             f"start {start[0]:.3f} {start[1]:.3f}",
             f"hard {hard[0]:.3f} {hard[1]:.3f} {hard[2]:.3f}"]
    for (x, y, sx, sy, h) in towers:
        lines.append(f"building {x:.3f} {y:.3f} {sx:.3f} {sy:.3f} {h:.3f}")
    for (x, y, sx, sy, h) in towers:
        lines.append(f"pillar {x:.3f} {y:.3f} {max(sx, sy) * 0.5:.3f}")
    for (x, y, r, h) in clutter:
        lines.append(f"pillar {x:.3f} {y:.3f} {r:.3f}")
    for (i, x, y) in markers:
        lines.append(f"amarker {i} {x:.3f} {y:.3f}")
    with open(os.path.join(PKG, "config", "metro_scene.txt"), "w") as f:
        f.write("\n".join(lines) + "\n")
    return len(buildings), len(towers) + len(clutter), len(markers)


if __name__ == "__main__":
    import sys
    os.makedirs(os.path.join(PKG, "config"), exist_ok=True)
    # `gen_maps.py real` rebuilds ONLY the real + real_dense maps, leaving the
    # sandbox demo/canopy worlds untouched (they are frozen per project constraint).
    if len(sys.argv) > 1 and sys.argv[1] == "real":
        ro, rm = build_real()
        rdo, rdm = build_real_dense()
        cb, ct, cm = build_city()
        mb, mt, mm = build_metro()
        print(f"real:       {ro} obstacles, {rm} ArUco markers (ids 0..{rm-1})")
        print(f"real_dense: {rdo} obstacles, {rdm} ArUco markers (ids 0..{rdm-1})")
        print(f"city:       {cb} buildings ({ct} tall enough to be obstacles), {cm} markers")
        print(f"metro:      {mb} buildings ({mt} obstacles), {mm} markers")
    else:
        do, dm = build_demo()
        co, cm = build_canopy()
        ro, rm = build_real()
        rdo, rdm = build_real_dense()
        print(f"demo:       {do} towers/buildings, {dm} markers")
        print(f"canopy:     {co} trees, {cm} markers")
        print(f"real:       {ro} obstacles, {rm} ArUco markers (ids 0..{rm-1})")
        print(f"real_dense: {rdo} obstacles, {rdm} ArUco markers (ids 0..{rdm-1})")
