// GENERATED by tools/gen_arena_world.py -- do not edit by hand.
// The arena scene shared by the Gazebo world and the navigator (kept in sync).
#ifndef FRUGALNAV_SCENE_ARENA_HPP
#define FRUGALNAV_SCENE_ARENA_HPP
#include <array>
#include <vector>
namespace frugalnav { namespace scene {
struct Pillar { float x, y, r; };
constexpr float START_X = 58.000f, START_Y = 24.000f;
constexpr float TARGET_X = 0.000f, TARGET_Y = 0.000f;
constexpr float HARD_X = 35.960f, HARD_Y = 14.880f, HARD_R = 8.000f;
inline const std::vector<Pillar> PILLARS = { {41.518f,14.582f,1.500f}, {31.409f,16.027f,1.500f}, {26.514f,8.158f,1.800f}, {16.482f,9.418f,1.500f}, {11.128f,2.657f,1.300f} };
inline const std::vector<std::array<float,2>> MARKERS = { {4.000f,0.000f}, {4.000f,7.000f}, {4.000f,14.000f}, {4.000f,21.000f}, {4.000f,28.000f}, {11.000f,7.000f}, {11.000f,14.000f}, {11.000f,21.000f}, {11.000f,28.000f}, {18.000f,0.000f}, {18.000f,14.000f}, {18.000f,21.000f}, {18.000f,28.000f}, {25.000f,0.000f}, {25.000f,14.000f}, {25.000f,21.000f}, {25.000f,28.000f}, {32.000f,0.000f}, {32.000f,7.000f}, {32.000f,21.000f}, {32.000f,28.000f}, {39.000f,0.000f}, {39.000f,7.000f}, {39.000f,21.000f}, {39.000f,28.000f}, {46.000f,0.000f}, {46.000f,7.000f}, {46.000f,14.000f}, {46.000f,21.000f}, {46.000f,28.000f}, {53.000f,0.000f}, {53.000f,7.000f}, {53.000f,14.000f}, {53.000f,21.000f}, {53.000f,28.000f}, {60.000f,0.000f}, {60.000f,7.000f}, {60.000f,14.000f}, {60.000f,21.000f}, {60.000f,28.000f} };
} }
#endif
